set(ASM_DIALECT "_UASM")
set(CMAKE_ASM${ASM_DIALECT}_SOURCE_FILE_EXTENSIONS asm)

set(CMAKE_ASM${ASM_DIALECT}_COMPILE_OBJECT "<CMAKE_ASM${ASM_DIALECT}_COMPILER> -D__MINGW32__ <DEFINES> <FLAGS> <INCLUDES> -Cp -Zm -Zv8 -Fo <OBJECT> <SOURCE>")

include(CMakeASMInformation)
set(ASM_DIALECT)
