name: linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        platform: [clang, gcc]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Configure CrashPad
      env:
          CC: ${{ steps.vars.outputs.cc }}
          CXX: ${{ steps.vars.outputs.cxx }}
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -B build
        
    - name: Build CrashPad
      run: |
        cmake --build build -- -j 4
