name: linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [clang, gcc]
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set variables
      id: vars
      run: |
        if [ "${{ matrix.platform }}" = "clang" ]
        then
          echo "::set-output name=cc::clang"
          echo "::set-output name=cxx::clang++"
        else
          echo "::set-output name=cc::gcc"
          echo "::set-output name=cxx::g++"
        fi

    - name: Configure CrashPad
      env:
          CC: ${{ steps.vars.outputs.cc }}
          CXX: ${{ steps.vars.outputs.cxx }}
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -B build
        
    - name: Build CrashPad
      run: |
        cmake --build build -- -j 4
