name: windows

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  windows_msvc:
    runs-on: windows-2019
    strategy:
      matrix:
        platform: [x86, amd64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
        
    - uses: ilammy/msvc-dev-cmd@v1.4.1
      with:
        arch: ${{ matrix.platform }}
        
    - name: Install Dependencies
      run: |
        Invoke-WebRequest -Uri https://github.com/ninja-build/ninja/releases/download/v1.10.1/ninja-win.zip -OutFile $Env:TEMP\ninja-win.zip
        Expand-Archive $Env:TEMP\ninja-win.zip -DestinationPath $Env:TEMP\ninja
        echo "$Env:TEMP\ninja" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        ninja --version
        
    - name: Configure CrashPad
      run: |
        cmake -G Ninja -B build

    - name: Build CrashPad
      run: |
        cmake --build build --config Release
